name: manage-azure-policy-518366a3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_export_to_Event_Hub_for_Microsoft_Defender_for_Cloud_data(secure)_ec30323b-a403-4008-9ba7-9e05291eb7c9/**'
#      - .github/workflows/manage-azure-policy-518366a3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_518366a3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_export_to_Event_Hub_for_Microsoft_Defender_for_Cloud_data(secure)_ec30323b-a403-4008-9ba7-9e05291eb7c9/**
